# Generated by Django 5.1.7 on 2025-03-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('undertitle', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Главный блок',
            },
        ),
    ]
