# Generated by Django 5.1.7 on 2025-03-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainblock',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='mainblock',
            old_name='title',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='mainblock',
            name='undertitle',
        ),
    ]
