# Generated by Django 5.1.7 on 2025-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_description_mainblock_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainblock',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mainblock',
            old_name='type',
            new_name='title',
        ),
        migrations.AddField(
            model_name='mainblock',
            name='undertitle',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
