# Generated by Django 5.1.7 on 2025-03-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_text_mainblock_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('undertitle', models.TextField()),
                ('description', models.TextField()),
                ('callToAction', models.TextField()),
                ('nameOfCEO', models.TextField()),
                ('CEO', models.TextField()),
                ('sign', models.FileField(upload_to='uploads/WelcomeBlock')),
            ],
            options={
                'verbose_name_plural': 'Приветственный блок',
            },
        ),
    ]
