# Generated by Django 5.1.7 on 2025-03-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_welcomeblock_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomeblock',
            name='sign',
            field=models.ImageField(upload_to='main/uploads/sign'),
        ),
    ]
