# Generated by Django 5.1.7 on 2025-03-26 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_welcomeblock_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='advantages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Картинка преимущества')),
            ],
            options={
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='CEO',
            field=models.TextField(verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='callToAction',
            field=models.TextField(verbose_name='Призыв к действию'),
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='nameOfCEO',
            field=models.TextField(verbose_name='ФИО Руководителя'),
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='sign',
            field=models.ImageField(upload_to='sign', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Картинка подписи'),
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='welcomeblock',
            name='undertitle',
            field=models.TextField(verbose_name='Подзаголовок'),
        ),
    ]
