# Generated by Django 5.1.7 on 2025-03-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_performance_poster_alter_performance_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Блок с преимуществами под видео',
            },
        ),
        migrations.RemoveField(
            model_name='performance',
            name='starText1',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='starText2',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='starText3',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='starText4',
        ),
    ]
