# Generated by Django 5.1.7 on 2025-03-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_performanceitems_remove_performance_startext1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('doc', models.FileField(upload_to='memo')),
            ],
            options={
                'verbose_name_plural': 'Памятки',
            },
        ),
        migrations.DeleteModel(
            name='Docs',
        ),
    ]
