# Generated by Django 5.1.7 on 2025-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_news_description_alter_news_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('parent', models.TextField(verbose_name='Родитель(ли)')),
                ('childAge', models.TextField(verbose_name='Возраст ребенка')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('fileUrl', models.FileField(upload_to='', verbose_name='Фото или видео отзыва')),
                ('published', models.BooleanField(verbose_name='Видимость')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
