# Generated by Django 5.1.7 on 2025-04-12 09:34

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='phoneNumber',
            field=models.TextField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='fileUrl',
            field=models.FileField(upload_to='reviews', verbose_name='Фото или видео отзыва'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.TextField(verbose_name='Имя ребенка'),
        ),
    ]
