# Generated by Django 5.1.7 on 2025-04-12 16:09

import django.core.validators
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_documentspage_alter_questions_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название филиала')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('timework', models.CharField(max_length=100, verbose_name='Время работы')),
                ('group', models.CharField(max_length=100, verbose_name='Возраст для группы')),
                ('count_child', models.CharField(max_length=100, verbose_name='До скольки детей идет набор')),
                ('new', models.BooleanField(verbose_name='Статус нового')),
            ],
            options={
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.AlterModelOptions(
            name='documentspage',
            options={'verbose_name_plural': 'Страница с документами'},
        ),
        migrations.CreateModel(
            name='FilialsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to=main.models.path_filials_news, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Картинка новости')),
                ('filials', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.filials')),
            ],
            options={
                'verbose_name_plural': 'Новости филиалов',
            },
        ),
        migrations.CreateModel(
            name='FilialsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Имя Отчество')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('status', models.CharField(max_length=100, verbose_name='Профессия')),
                ('expirience', models.CharField(max_length=50, verbose_name='Количество опыта')),
                ('quote', models.TextField(verbose_name='Цитата')),
                ('image', models.ImageField(upload_to=main.models.path_filials_team, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='Описание')),
                ('callToAction', models.TextField(verbose_name='Призыв к действию')),
                ('filials', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.filials')),
            ],
            options={
                'verbose_name_plural': 'Работники филиалов',
            },
        ),
    ]
