# Generated by Django 5.1.7 on 2025-04-12 16:19

import django.core.validators
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_filials_alter_documentspage_options_filialsnews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filials',
            name='new',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус нового'),
        ),
        migrations.AlterField(
            model_name='filialsnews',
            name='filials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.filials'),
        ),
        migrations.AlterField(
            model_name='filialsnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.path_filials_news, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Картинка новости'),
        ),
        migrations.AlterField(
            model_name='filialsteam',
            name='callToAction',
            field=models.TextField(blank=True, null=True, verbose_name='Призыв к действию'),
        ),
        migrations.AlterField(
            model_name='filialsteam',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='filialsteam',
            name='filials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.filials'),
        ),
        migrations.AlterField(
            model_name='filialsteam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.path_filials_team, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='filialsteam',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='Цитата'),
        ),
    ]
