# Generated by Django 5.1.7 on 2025-04-12 16:35

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_filials_new_alter_filialsnews_filials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filialsnews',
            name='image',
            field=models.ImageField(default=1, upload_to=main.models.path_filials_news, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Картинка новости'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filialsteam',
            name='image',
            field=models.ImageField(default=1, upload_to=main.models.path_filials_team, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
