# Generated by Django 5.1.7 on 2025-04-12 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_filialsnews_image_alter_filialsteam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='filials',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filialsnews',
            name='filials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.filials'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filialsteam',
            name='filials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.filials'),
            preserve_default=False,
        ),
    ]
