# Generated by Django 5.1.7 on 2025-04-12 17:05

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_filials_slug_alter_filialsnews_filials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filials',
            name='poster',
            field=models.ImageField(default='', upload_to=main.models.path_filial_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью видео'),
        ),
    ]
