# Generated by Django 5.1.7 on 2025-04-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_filials_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentspage',
            name='page',
            field=models.CharField(choices=[('GLK', 'ООО «Золотой ключик»'), ('BSH', 'ИП Башаева М.Р.')], default='GLK', max_length=3),
        ),
    ]
