# Generated by Django 5.1.7 on 2025-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_documentspage_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('phoneNumber', models.CharField(max_length=25, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('policy', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
            ],
            options={
                'verbose_name_plural': 'Отправленния пособия для адаптации',
            },
        ),
    ]
