# Generated by Django 5.1.7 on 2025-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_booksend'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksend',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправления'),
        ),
    ]
