# Generated by Django 5.1.7 on 2025-04-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_booksend_send_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=300, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
                ('pdf', models.FileField(upload_to='setting/sendBook')),
            ],
            options={
                'verbose_name_plural': 'Настройка рассылки пособия',
            },
        ),
    ]
