# Generated by Django 5.1.7 on 2025-04-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_emailsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('phoneNumber', models.CharField(max_length=25, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('policy', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('send_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправления')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.filials')),
            ],
        ),
    ]
