# Generated by Django 5.1.7 on 2025-04-14 09:33

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_excursionfilial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursionfilial',
            options={'verbose_name_plural': 'Запись на экскурсию'},
        ),
        migrations.AddField(
            model_name='filials',
            name='video',
            field=models.FileField(default=1, upload_to=main.models.path_filial_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('MOV', 'avi', 'mp4', 'webm', 'mkv'))], verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
