# Generated by Django 5.1.7 on 2025-04-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_excursionfilial_options_filials_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentspage',
            name='isTitle',
            field=models.BooleanField(default=True, verbose_name='Отображение заголовка'),
        ),
    ]
